src/Presentation/SmartStore.Web/Models/Media/MediaGalleryModel.cs
using System.Collections.Generic;
using SmartStore.Services.Media;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Media
{
    public partial class MediaGalleryModel : ModelBase
    {
        public IList<MediaFileInfo> Files { get; set; } = new List<MediaFileInfo>();
        public int GalleryStartIndex { get; set; }
        public int ThumbSize { get; set; } = 72;
        public int ImageSize { get; set; } = 600;
        public string FallbackUrl { get; set; }

        public string ModelName { get; set; }
        public string DefaultAlt { get; set; }

        public bool BoxEnabled { get; set; }
        public bool ImageZoomEnabled { get; set; }
        public string ImageZoomType { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Media/PictureModel.cs
using SmartStore.Services.Media;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Media
{
    public partial class PictureModel : ModelBase
    {
        public int PictureId { get; set; }
        public int? Size { get; set; }
        public string ThumbImageUrl { get; set; }
        public string ImageUrl { get; set; }
        public string FullSizeImageUrl { get; set; }
        public int? FullSizeImageWidth { get; set; }
        public int? FullSizeImageHeight { get; set; }
        public string Title { get; set; }
        public string AlternateText { get; set; }

        public MediaFileInfo File { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.SessionState;
using SmartStore.Core;
using SmartStore.Core.Domain.Media;
using SmartStore.Core.Domain.Seo;
using SmartStore.Core.Events;
using SmartStore.Core.Infrastructure;
using SmartStore.Core.IO;
using SmartStore.Core.Logging;
using SmartStore.Core.Security;
using SmartStore.Services.Media;
using SmartStore.Services.Media.Imaging;
using SmartStore.Services.Seo;
using SmartStore.Utilities;
using SmartStore.Web.Framework.Localization;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Seo;

namespace SmartStore.Web.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    [OverrideAuthentication]
    [OverrideAuthorization]
    [OverrideResultFilters]
    //[OverrideActionFilters] // TBD: (mc) really?
    [OverrideExceptionFilters]
    public partial class MediaController : Controller
    {
        //private readonly static bool _streamRemoteMedia = CommonHelper.GetAppSetting<bool>("sm:StreamRemoteMedia");

        private readonly IMediaService _mediaService;
        private readonly IFolderService _folderService;
        private readonly IPermissionService _permissionService;
        private readonly IEventPublisher _eventPublisher;
        private readonly IWorkContext _workContext;
        private readonly MediaSettings _mediaSettings;
        private readonly MediaHelper _mediaHelper;

        private readonly Lazy<IEnumerable<IMediaHandler>> _mediaHandlers;
        private readonly Lazy<SeoSettings> _seoSettings;
        private readonly Lazy<IXmlSitemapGenerator> _sitemapGenerator;

        public MediaController(
            IMediaService mediaService,
            IFolderService folderService,
            IPermissionService permissionService,
            IEventPublisher eventPublisher,
            IWorkContext workContext,
            MediaSettings mediaSettings,
            MediaHelper mediaHelper,
            Lazy<IEnumerable<IMediaHandler>> mediaHandlers,
            Lazy<SeoSettings> seoSettings,
            Lazy<IXmlSitemapGenerator> sitemapGenerator)
        {
            _mediaService = mediaService;
            _folderService = folderService;
            _permissionService = permissionService;
            _eventPublisher = eventPublisher;
            _workContext = workContext;
            _mediaSettings = mediaSettings;
            _mediaHelper = mediaHelper;
            _mediaHandlers = mediaHandlers;
            _seoSettings = seoSettings;
            _sitemapGenerator = sitemapGenerator;
        }

        public ILogger Logger { get; set; } = NullLogger.Instance;

        #region XML sitemap

        [RewriteUrl(SslRequirement.No)]
        [LanguageSeoCode(Order = 1)]
        [SetWorkingCulture(Order = 2)]
        public async Task<ActionResult> XmlSitemap(int? index = null)
        {
            if (!_seoSettings.Value.XmlSitemapEnabled)
                return HttpNotFound();

            try
            {
                var partition = await _sitemapGenerator.Value.GetSitemapPartAsync(index ?? 0);
                return new FileStreamResult(partition.Stream, "text/xml");
            }
            catch (IndexOutOfRangeException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Sitemap index is out of range.");
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }
        }

        #endregion

        /// <summary>
        /// Redirect legacy URL "/uploaded/some/file.png" to "/file/1234/some/file.png"
        /// </summary>
        public ActionResult Uploaded(string path)
        {
            path = SystemAlbumProvider.Files + "/" + path;

            var mediaFile = _mediaService.GetFileByPath(path, MediaLoadFlags.AsNoTracking);
            if (mediaFile == null)
            {
                return NotFound(null);
            }

            var routeValues = new RouteValueDictionary(RouteData.Values)
            {
                ["id"] = mediaFile.Id,
                ["path"] = path
            };

            return RedirectToActionPermanent("File", routeValues);
        }

        /// <summary>
        /// Redirect legacy URL "/media/image/234/file.png" to "/media/234/catalog/path/to/file.png"
        /// </summary>
        [AcceptVerbs("GET", "HEAD")]
        public ActionResult Image(string path)
        {
            var segments = path.SplitSafe("/");

            if (!segments.Any() || !CommonHelper.TryConvert(segments[0], CultureInfo.InvariantCulture, out int fileId))
            {
                return NotFound(null);
            }

            var file = _mediaService.GetFileById(fileId, MediaLoadFlags.AsNoTracking);
            if (file == null)
            {
                return NotFound(null);
            }

            var routeValues = new RouteValueDictionary(RouteData.Values)
            {
                ["id"] = file.Id,
                ["path"] = file.Path
            };

            var qs = Request.QueryString;
            qs.AllKeys.Each(key => routeValues.Add(key, qs[key]));

            return RedirectToActionPermanent("File", routeValues);
        }

        [AcceptVerbs("GET", "HEAD")]
        public async Task<ActionResult> File(int id /* mediaFileId */, string path)
        {
            MediaFileInfo mediaFile = null;
            MediaPathData pathData = null;

            if (id == 0)
            {
                // This is most likely a request for a default placeholder image
                pathData = new MediaPathData(path);
            }
            else if (!_mediaHelper.TokenizePath(path, false, out pathData))
            {
                // Missing or malformed Uri: get file metadata from DB by id, but only when current user has media manage rights
                if (!_permissionService.Authorize(Permissions.Media.Update))
                {
                    return NotFound(null);
                }

                mediaFile = _mediaService.GetFileById(id, MediaLoadFlags.AsNoTracking);
                if (mediaFile == null || mediaFile.FolderId == null || mediaFile.Deleted)
                {
                    return NotFound(mediaFile?.MimeType);
                }

                pathData = new MediaPathData(_folderService.GetNodeById(mediaFile.FolderId.Value), mediaFile.Name)
                {
                    Extension = mediaFile.Extension,
                    MimeType = mediaFile.MimeType
                };
            }

            var q = CreateImageQuery(pathData.MimeType, pathData.Extension);

            // Security: check allowed thumnail sizes and return 404 if disallowed.
            var thumbSizeAllowed = IsThumbnailSizeAllowed(q.MaxWidth) && (q.MaxHeight == q.MaxWidth || IsThumbnailSizeAllowed(q.MaxHeight));
            if (!thumbSizeAllowed)
            {
                return NotFound(pathData.MimeType);
            }

            var handlerContext = new MediaHandlerContext
            {
                HttpContext = HttpContext,
                CurrentCustomer = _workContext.CurrentCustomer,
                PermissionService = _permissionService,
                MediaFileId = id,
                RawPath = path,
                MediaService = _mediaService,
                PathData = pathData,
                SourceFile = mediaFile,
                ImageQuery = q
            };

            var handlers = _mediaHandlers.Value.OrderBy(x => x.Order).ToArray();

            IMediaHandler currentHandler;
            for (var i = 0; i < handlers.Length; i++)
            {
                currentHandler = handlers[i];

                // Execute handler
                await currentHandler.ExecuteAsync(handlerContext);

                if (handlerContext.Exception != null)
                {
                    var isThumbExtractFail = handlerContext.Exception is ExtractThumbnailException;
                    var statusCode = isThumbExtractFail ? HttpStatusCode.NoContent : HttpStatusCode.InternalServerError;
                    var statusMessage = isThumbExtractFail ? handlerContext.Exception.InnerException?.Message.EmptyNull() : handlerContext.Exception.Message;

                    return new HttpStatusCodeResult(statusCode, statusMessage);
                }

                if (handlerContext.Executed || handlerContext.ResultFile != null)
                {
                    // Get out if the handler produced a result file or has been executed in any way
                    break;
                }
            }

            try
            {
                var responseFile = handlerContext.ResultFile ?? handlerContext.SourceFile;
                if (responseFile == null || !responseFile.Exists)
                {
                    return NotFound(pathData.MimeType);
                }

                if (string.Equals(responseFile.Extension, "." + pathData.Extension, StringComparison.CurrentCultureIgnoreCase))
                {
                    pathData.MimeType = MimeTypes.MapNameToMimeType(responseFile.Extension);
                }

                return new CachedFileResult(responseFile, pathData.MimeType);
            }
            finally
            {
                Debug.WriteLine("ImageProcessor TOTAL: {0} ms.".FormatCurrent(EngineContext.Current.Resolve<IImageProcessor>().TotalProcessingTimeMs));
            }
        }

        private bool IsThumbnailSizeAllowed(int? size)
        {
            return size.GetValueOrDefault() == 0
                || _mediaSettings.IsAllowedThumbnailSize(size.Value)
                || _permissionService.Authorize(Permissions.Media.Update, _workContext.CurrentCustomer);
        }

        private ActionResult NotFound(string mime)
        {

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Boolean.cshtml
@functions{    
    private bool? Value
    {
        get
        {
            bool? value = null;
            if (ViewData.Model != null)
            {
                value = Convert.ToBoolean(ViewData.Model, System.Globalization.CultureInfo.InvariantCulture);
            }
            return value;
        }
    }

    private List<SelectListItem> TriStateValues
    {
        get
        {
            return new List<SelectListItem> {
                new SelectListItem { Text = T("Common.Unspecified").ToString(), Value = String.Empty, Selected = !Value.HasValue },
                new SelectListItem { Text = T("Common.Yes").ToString(), Value = "true", Selected = Value.HasValue && Value.Value },
                new SelectListItem { Text = T("Common.No").ToString(), Value = "false", Selected = Value.HasValue && !Value.Value },
            };
        }
    }
}


@if (!ViewData.ModelMetadata.IsNullableValueType)
{
    @Html.CheckBox(string.Empty, Value ?? false, new { @class = "check-box form-check-input" })
}
else
{
    @Html.DropDownList(string.Empty, TriStateValues, new { @class = "form-control list-box tri-state" })
}

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/ButtonType.cshtml
@model string
@functions{
	private string Value
	{
		get
		{
			string value = null;
			if (ViewData.Model != null)
			{
				value = Convert.ToString(ViewData.Model);
			}
			return value;
		}
	}

	private List<SelectListItem> ButtonTypes
	{
		get
		{
			return new List<SelectListItem> {
				new SelectListItem { Text = T("Common.Buttons.Secondary").ToString(), Value = "btn-secondary", Selected = (Value == "btn-secondary") },
				new SelectListItem { Text = T("Common.Buttons.Primary").ToString(), Value = "btn-primary", Selected = (Value == "btn-primary") },
				new SelectListItem { Text = T("Common.Buttons.Info").ToString(), Value = "btn-info", Selected = (Value == "btn-info") },
				new SelectListItem { Text = T("Common.Buttons.Success").ToString(), Value = "btn-success", Selected = (Value == "btn-success") },
				new SelectListItem { Text = T("Common.Buttons.Warning").ToString(), Value = "btn-warning", Selected = (Value == "btn-warning") },
				new SelectListItem { Text = T("Common.Buttons.Danger").ToString(), Value = "btn-danger", Selected = (Value == "btn-danger") },
				new SelectListItem { Text = T("Common.Buttons.Link").ToString(), Value = "btn-link", Selected = (Value == "btn-link") },
				new SelectListItem { Text = T("Common.Buttons.Light").ToString(), Value = "btn-light", Selected = (Value == "btn-light") },
				new SelectListItem { Text = T("Common.Buttons.Dark").ToString(), Value = "btn-dark", Selected = (Value == "btn-dark") },
			};
		}
	}
}

@{
    var id = ViewData.TemplateInfo.GetFullHtmlFieldId(string.Empty);
    var name = ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty);
}

@Html.DropDownList(string.Empty, ButtonTypes, new { @value = Value, @class = "form-control" })

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Byte.cshtml
@using Telerik.Web.Mvc.UI

@functions{
	private byte? Value
	{
		get
		{
			byte? value = null;
			if (ViewData.Model != null)
			{
				value = Convert.ToByte(ViewData.Model, System.Globalization.CultureInfo.InvariantCulture);
			}
			return value;
		}
	}

	private string CssClass
	{
		get
		{
			var cls = "numerictextbox-group flex-grow-1";

			if (TryGetMetadata<string>("size", out var size))
			{
				cls += " numerictextbox-group-" + size;
			}

			return cls;
		}
	}
}

<div class="@CssClass">
	@(Html.Telerik().NumericTextBox<byte>()
			.Name(ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty))
			.EmptyMessage(GetMetadata<string>("placeholder") ?? T("Common.EnterValue"))
            .ButtonTitleUp(T("Common.IncreaseValue"))
            .ButtonTitleDown(T("Common.DecreaseValue"))
			.MinValue(GetMetadata<byte?>("min") ?? 0)
			.MaxValue(GetMetadata<byte?>("max") ?? 255)
			.IncrementStep(GetMetadata<byte?>("step") ?? 1)
            .DecimalDigits(0)
			.Value(Value)
	)

	@if (TryGetMetadata<string>("postfix", out var postfix))
	{
		<span class="numerictextbox-postfix">@postfix</span>
	}
</div>

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Color.cshtml
@functions{   
	private string Value
	{
		get
		{
			string value = null;
			if (ViewData.Model != null)
			{
				value = Convert.ToString(ViewData.Model);
			}
			return value;
		}
	}
}

@Html.ColorBox("", Value.EmptyNull(), ViewData["fallbackColor"].Convert<string>())

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/DateTime.cshtml
@functions{   
	private DateTime? Value
	{
		get
		{
			DateTime? value = null;
			if (ViewData.Model != null)
			{
				value = Convert.ToDateTime(ViewData.Model, System.Globalization.CultureInfo.CurrentCulture);
			}
			return value;
		}
	}

	private bool PickTime
	{
		get
		{
			if (ViewData.ContainsKey("pickTime"))
			{
				return ViewData["pickTime"].Convert<bool>();
			}
			else if (ViewData.ContainsKey("pickTimeFieldIds"))
			{
				var ids = ViewData["pickTimeFieldIds"] as List<string>;
				var id = ViewData.TemplateInfo.GetFullHtmlFieldId(string.Empty);
				return ids.Contains(id);
			}
			return false;
		}
	}

	private string CssClass
	{
		get
		{
			var cls = "input-group date datetimepicker-group";

			if (ViewData.ContainsKey("size"))
			{
				cls += " input-group-" + ViewData["size"].Convert<string>();
			}

			return cls;
		}
	}
}

@{
    var id = ViewData.TemplateInfo.GetFullHtmlFieldId(string.Empty);
	var format = PickTime ? "L LT" : "L";
    var value = String.Empty;
    if (Value.HasValue && Value.Value > DateTime.MinValue)
	{
		value = PickTime ? Value.Value.ToString() : Value.Value.ToShortDateString();
    }
}

<div class="@CssClass" id="@id-parent" data-date="@value" data-target-input="nearest">
    @Html.TextBox("", value, new { @class = "form-control datetimepicker-input", data_target = "#" + id + "-parent", data_format = format })
	<div class="input-group-append input-group-addon" data-target="#@(id)-parent" data-toggle="datetimepicker">
		<span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
	</div>
</div>

<script data-origin="DateTime">
	$(function () {
		$("#@(id)-parent").datetimepicker({ format: '@(format)', useCurrent: false, locale: moment.locale() });
	});
</script>

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Decimal.cshtml
@using Telerik.Web.Mvc.UI

@functions{
	private decimal? Value
	{
		get
		{
			decimal? value = null;
			if (ViewData.Model != null)
			{
				value = Convert.ToDecimal(ViewData.Model, System.Globalization.CultureInfo.InvariantCulture);
			}
			return value;
		}
	}

	private string CssClass
	{
		get
		{
			var cls = "numerictextbox-group flex-grow-1";

			if (TryGetMetadata<string>("size", out var size))
			{
				cls += " numerictextbox-group-" + size;
			}

			return cls;
		}
	}
}

<div class="@CssClass">
	@(Html.Telerik().NumericTextBox<decimal>()
			.Name(ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty))
			.EmptyMessage(GetMetadata<string>("placeholder") ?? T("Common.EnterValue"))
            .ButtonTitleUp(T("Common.IncreaseValue"))
            .ButtonTitleDown(T("Common.DecreaseValue"))
			.Value(Value)
			.MinValue(GetMetadata<decimal?>("min"))
			.MaxValue(GetMetadata<decimal?>("max"))
			.IncrementStep(GetMetadata<decimal?>("step") ?? 1)
			.DecimalDigits(4)   //always display 4 digits
	)

	@if (TryGetMetadata<string>("postfix", out var postfix))
	{
		<span class="numerictextbox-postfix">@postfix</span>
	}
</div>

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Double.cshtml
@using Telerik.Web.Mvc.UI

@functions{
	private double? Value
	{
		get
		{
			double? value = null;
			if (ViewData.Model != null)
			{
				value = Convert.ToDouble(ViewData.Model, System.Globalization.CultureInfo.InvariantCulture);
			}
			return value;
		}
	}

	private string CssClass
	{
		get
		{
			var cls = "numerictextbox-group flex-grow-1";

			if (TryGetMetadata<string>("size", out var size))
			{
				cls += " numerictextbox-group-" + size;
			}

			return cls;
		}
	}
}

<div class="@CssClass">
	@(Html.Telerik().NumericTextBox<double>()
			.Name(ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty))
			.EmptyMessage(GetMetadata<string>("placeholder") ?? T("Common.EnterValue"))
            .ButtonTitleUp(T("Common.IncreaseValue"))
            .ButtonTitleDown(T("Common.DecreaseValue"))
			.Value(Value)
			.MinValue(GetMetadata<double?>("min"))
			.MaxValue(GetMetadata<double?>("max"))
			.IncrementStep(GetMetadata<double?>("step") ?? 1)
			.DecimalDigits(4)   //always display 4 digits
	)

	@if (TryGetMetadata<string>("postfix", out var postfix))
	{
		<span class="numerictextbox-postfix">@postfix</span>
	}
</div>

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Html.cshtml
@model String
@using SmartStore.Web.Framework.UI;
@{
	Html.AddScriptParts("~/bundles/codemirror");
	Html.AddCssFileParts("~/css/codemirror");

	Html.AddScriptParts("~/bundles/summernote");
	Html.AppendCssFileParts(true, "~/Content/editors/summernote/summernote-bs4.css");

	var lazy = ViewData["lazy"].Convert<bool?>() ?? true;
	var id = ViewData.TemplateInfo.GetFullHtmlFieldId(string.Empty);
	var html = ((string)ViewData.TemplateInfo.FormattedModelValue);
	var htmlIsEmpty = !html.HasValue() || html == "<p></p>" || html == "<p>&nbsp;</p>" || html == "<p><br></p>";

	// Find summernote localization file
	string culture = null;
	var locFile = base.ResolveLocalizationFile(WorkContext.WorkingLanguage.LanguageCulture, "~/Content/editors/summernote/lang", "summernote-*.js", null);
	if (locFile != null)
	{
		culture = locFile.Culture;
		Html.AddScriptParts(true, locFile.VirtualPath);
	}

	// Find custom plugins localization file
	locFile = base.ResolveLocalizationFile(WorkContext.WorkingLanguage.LanguageCulture, "~/Content/editors/summernote/plugins/lang", "*.js", null);
	if (locFile != null)
	{
		Html.AddScriptParts(true, locFile.VirtualPath);
	}

	Html.AddBodyAttribute("data-file-manager-url", base.FileManagerUrl);
}

<div class="html-editor-root">
	@Html.TextArea(string.Empty /* Name suffix */, html /* Initial value */, new { @class = "summernote-editor" + (lazy ? " d-none" : "") })

	@if (lazy)
	{
		<div class="note-editor-preview@(htmlIsEmpty ? " empty" : "")" data-target="#@id" @Html.Attr("data-lang", culture, culture != null)>
			@if (htmlIsEmpty)
			{
				<div>
					<i class="fab fa-html5 mr-1"></i>
					<span class="text-muted">@T("HtmlEditor.ClickToEdit")</span>
				</div>
			}
			else
			{
				@Html.Raw(html)
			}
		</div>
	}
</div>


<script>
	summernote_image_upload_url = '@Html.Raw(Url.Action("ProcessRequest", "RoxyFileManager"))';
	@if (!lazy)
	{
		<text>
			$(function () {
				$('#@id').summernote($.extend(true, {}, summernote_global_config, { lang: @Html.Raw(culture != null ? "'" + culture + "'" : "null") }));
			});
		</text>
	}
</script>

src/Presentation/SmartStore.Web/Views/Shared/EditorTemplates/Media.cshtml
@model int?

@using SmartStore.Core.Domain.Media;
@using SmartStore.Core.Domain.Catalog;
@using SmartStore.Services.Media;
@using SmartStore.Web.Framework.UI;
@using SmartStore.Utilities;

@functions {
    private bool TransientUpload
    {
        get
        {
            return GetMetadata<bool>("transientUpload");
        }
    }

    private bool ShowBrowseMedia
    {
        get
        {
            return GetMetadata<bool>("showBrowseMedia", true);
        }
    }

    private string Path
    {
        get
        {
            return GetMetadata<string>("path") ?? GetMetadata<string>("album");
        }
    }

    private string TypeFilter
    {
        get
        {
            return GetMetadata<string>("typeFilter", "image");
        }
    }

    private int EntityId
    {
        get
        {
            return GetMetadata<int>("entityId");
        }
    }

    private string EntityType
    {
        get
        {
            return GetMetadata<string>("entityType");
        }
    }

    private string DeleteUrl
    {
        get
        {
            return GetMetadata<string>("deleteUrl");
        }
    }

    private string SortUrl
    {
        get
        {
            return GetMetadata<string>("sortUrl");
        }
    }

    private string EntityAssignmentUrl
    {
        get
        {
            return GetMetadata<string>("entityAssignmentUrl");
        }
    }

    private bool MultiFile
    {
        get
        {
            return GetMetadata<bool>("multifile");
        }
    }

    private IEnumerable<IMediaFile> UploadedFiles
    {
        get
        {
            return GetMetadata<IEnumerable<IMediaFile>>("uploadedFiles");
        }
    }
}

@{
    var random = CommonHelper.GenerateRandomInteger();
    var mediaService = this.CommonServices.MediaService;
    var currentFile = Model != null ? mediaService.GetFileById((int)Model) : null;
    var defaultValue = Model != null ? 0 : (int?)null;
}

<div class="fu-container@(MultiFile ? " xl" : "")">
    <div @Html.Attr("class", "dropzone-container", !MultiFile)>

        @if (!MultiFile)
        {
            // Single file uploads have preview images.
            <div class="fu-thumb fu-filename rounded" data-current-filename="@(currentFile?.Name)">
                @Html.MediaThumbnail(currentFile, MediaSettings.ThumbnailSizeMd)
            </div>
            @Html.HiddenFor(x => x, new { @class = "hidden", Value = currentFile != null ? Model : defaultValue })
        }

        <div class="fu-controls">
            @(Html.SmartStore().FileUploader()
                .UploadUrl(Url.Action("Upload", "Media", new { isTransient = TransientUpload, path = Path, area = "Admin" }))
                .Path(Path)
                .TypeFilter(TypeFilter)
                .ShowRemoveButton(!MultiFile && Model.HasValue) // Multifile uploads don't need a remove button.
                .ShowRemoveButtonAfterUpload(true)
                .PreviewContainerId("preview-" + random)
                .Multifile(MultiFile)
                .MainFileId(Model)
                .ShowBrowseMedia(ShowBrowseMedia)
                .HasTemplatePreview(true)
                .UploadedFiles(UploadedFiles)
                .EntityType(EntityType)
                .EntityId(EntityId)
                .DeleteUrl(DeleteUrl)
                .SortUrl(SortUrl)
                .EntityAssignmentUrl(EntityAssignmentUrl)
            )
        </div>
    </div>

	<div class="fu-progress">
		<!-- The single upload progress bar -->
		<div class="progress">
			<div class="progress-bar" role="progressbar" style="width: 0%" aria-valuemin="0" aria-valuemax="100"></div>
		</div>
	</div>
</div>